# Generated by Django 3.0.8 on 2020-10-02 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Eliminacion')),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Pelcula',
                'verbose_name_plural': 'Tipos de Pelculas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Pelicula')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='Poster Pelicula')),
                ('sipnosis', models.TextField(verbose_name='Sipnosis')),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Duracion pelicula')),
                ('clasificacion', models.CharField(choices=[('T', 'Todo Publico'), ('N', 'Niños menores de 12 años'), ('A', 'Mayores de 18 años')], default='T', max_length=1, verbose_name='Clasificacion Pelicula')),
                ('trailer', models.URLField(max_length=500, verbose_name='Trailer Pelicula')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Eliminacion')),
                ('tipoPelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmovies.TipoPelicula')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pelcula',
                'verbose_name_plural': 'Pelculas',
                'ordering': ['titulo'],
            },
        ),
    ]
